name: how_much
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4
  firebase_remote_config: ^4.3.8
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.6

  # Sign in
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0

  # Mobx
  mobx: ^2.2.3
  build_runner: ^2.4.7
  flutter_mobx: ^2.2.0+1
  mobx_codegen: ^2.4.0

  # DI
  get_it: ^7.6.4

  # Storage
  shared_preferences: ^2.2.2

  # Animation
  flutter_animate: ^4.3.0
  flutter_spinkit: ^5.2.0

  # Http
  dio: ^5.4.0

  # General
  intl: ^0.18.0
  currency_text_input_formatter: ^2.1.10
  dartz: ^0.10.1
  equatable: ^2.0.5  
  gradient_borders: ^1.0.0

  # URL
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true